apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-crds
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: strimzi
  project: default
  source:
    repoURL: https://github.com/strimzi/strimzi-kafka-operator.git
    path: helm-charts/helm3/strimzi-kafka-operator/crds
    targetRevision: 0.35.1
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
