loki-stack:
  enabled: true
  test_pod:
    enabled: false
  promtail:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-log:3100/loki/api/v1/push
  loki:
    fullnameOverride: loki-log
    persistence:
      enabled: false
    config:
    alerting_groups: []

  grafana:
    enabled: true
    fullnameOverride: loki-log-grafana
    envRenderSecret: {}
    admin:
      existingSecret: "grafana-credentials"
      userKey: GRAFANA_USER
      passwordKey: GRAFANA_PASSWORD
    image:
      tag: 8.5.13

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: Server
          url: http://loki-log.loki-log.svc.cluster.local:3100

        - name: Tempo
          type: tempo
          access: Server
          url: http://tempo.tempo.svc.cluster.local:3100
