apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promftp
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'promftp-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/PROMDevOps/PROMFTP-Deployment.git
        targetRevision: "{{name}}" #Based on environment
        path: 'promftp-common'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
            - values-tags-{{name}}.yaml
            - values-uploader-tags-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: promftp-{{name}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
