apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'echo-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/its-software-services-devops/promrub-argocd-apps.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/echo'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: echo
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
