apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opensearch-operator
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'opensearch-operator-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/PROMDevOps/PROM-K3S-Addons.git
        targetRevision: "{{name}}" #Based on environment
        path: 'manifests/opensearch-operator'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: opensearch-operator
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
