apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promjodd-v2
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'promjodd-v2-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/PROMDevOps/PROMJODD-V2-Deployment.git
        targetRevision: "{{name}}" #Based on environment
        path: 'promjodd-v2-common'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            - values-{{name}}.yaml
            - values-tags-{{name}}.yaml
            - values-webportal-tags-{{name}}.yaml
            - values-lprweb-tags-{{name}}.yaml
      destination:
        name: in-cluster
        namespace: promjodd-v2-{{name}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
