apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-crds
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: strimzi
  project: default
  source:
    path: https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.35.1/strimzi-crds-0.35.1.yaml
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
