---
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret-wtt
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
stringData:
  url: https://github.com/wintech-thai/WTT-Web-Deployment.git
  #username: dummy-gh
  #password: 'notused-because-it-is-public'
  type: git
