---
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret-analytic
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
stringData:
  url: https://github.com/PROMDevOps/ANALYTIC-Deployment.git
  #username: dummy-gh
  #password: 'notused-because-it-is-public'
  type: git
