ingress-nginx:
  enabled: true

  controller:
    service:
      #externalTrafficPolicy: "Local"
      enabled: true
      type: NodePort
      nodePorts:
        https: 32443
        http: 32080

    config:
      enable-real-ip: "true"
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "true"
      proxy-add-original-uri-header: "true"
