kong:
  enabled: true
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true

konga:
  fullnameOverride: konga
  enabled: true
