apiVersion: v2
name: helm-tempo
version: 1.0.0
appVersion: 1.25.0
description: A Helm chart wrapper for Tempo

dependencies:
  - name: "tempo"
    alias: tempo
    condition: tempo.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "1.3.1"
