---
# Source: helm-kong/charts/konga/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  konga-config
  labels:
    app.kubernetes.io/name: konga
    helm.sh/chart: konga-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
---
# Source: helm-kong/charts/konga/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-konga
  labels:
    app.kubernetes.io/name: konga
    helm.sh/chart: konga-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: konga
    app.kubernetes.io/instance: release-name
---
# Source: helm-kong/charts/konga/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-konga
  labels:
    app.kubernetes.io/name: konga
    helm.sh/chart: konga-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: konga
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: konga
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: konga
          image: "pantsel/konga:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
            - configMapRef:
                name: konga-config
          resources:
            {}
---
# Source: helm-kong/charts/konga/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-konga-test-connection"
  labels:
    app.kubernetes.io/name: konga
    helm.sh/chart: konga-1.0.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-konga:80']
  restartPolicy: Never
