domain: grafana-k8s.promrub.prom.co.th
domain1: alm.promrub.prom.co.th
domain2: prom.promrub.prom.co.th

environment: production

kube-prometheus-stack:
  grafana:
    grafana.ini:
      server:
        root_url: grafana-k8s.promrub.prom.co.th
    grafana.ini:
      server:
        root_url: https://grafana-k8s.promrub.prom.co.th
        domain: grafana-k8s.promrub.prom.co.th
