apiVersion: v2
name: helm-opensearch-operator
version: 1.0.0
appVersion: 1.25.0
description: A Helm chart wrapper for Opensearch Operator

dependencies:
  - name: "opensearch-operator"
    alias: opensearch-operator
    condition: opensearch-operator.enabled
    repository: "https://opster.github.io/opensearch-k8s-operator/"
    version: "2.4.0"
