echo:
  nameOverride: echo
  enabled: true
  podDisruptionBudget:
    enabled: false
  pods:
    controller: deployment
    image:
      name: "ealen/echo-server"
      tag: "0.7.0"
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    env: []
  ingress:
    enabled: false

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
