apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: scb-service
      url: https://promrub-scb.prom.co.th/
      routes:
      - name: scb
        strip_path: true
        paths:
        - /scb/

    - name: google-service
      url: https://google.com/
      routes:
      - name: google
        strip_path: true
        paths:
        - /google/

    - name: echo-service
      # TODO : Change this per environment
      url: http://echo-development.echo.svc.cluster.local/
      routes:
      - name: echo
        strip_path: true
        paths:
        - /echo/
