apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    # TODO : Path rewrite
    - name: scb-service
      url: https://promrub-scb.prom.co.th/
      routes:
      - name: scb
        strip_path: true
        paths:
        - /scb/

    - name: google-service
      url: https://google.com/
      routes:
      - name: google
        strip_path: true
        paths:
        - /google/
