apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: echo-service
      url: https://promrub-scb.prom.co.th/
      routes:
      - name: echo
        paths:
        - /echo
